"""Markdown export for run traces."""

from __future__ import annotations

from typing import Any

from agentux.core.models import RunTrace


def export_markdown(trace: RunTrace, analysis: dict[str, Any] | None = None) -> str:
    """Export a run trace as a Markdown summary."""
    lines = [
        f"# AgentUX Run Report: {trace.run_id}",
        "",
        f"**Target:** {trace.target}",
        f"**Task:** {trace.task}",
        f"**Surface:** {trace.surface_type.value}",
        f"**Model:** {trace.model or 'mock'}",
        f"**Backend:** {trace.backend}",
        f"**Status:** {'PASSED' if trace.success else 'FAILED'}",
        f"**Steps:** {trace.step_count}",
        f"**Tokens:** {trace.total_tokens}",
        f"**Duration:** {trace.duration_ms:.0f}ms",
        "",
        "## Scores",
        "",
        "| Metric | Score | Explanation |",
        "|--------|------:|-------------|",
    ]

    for key, result in trace.scores.as_dict().items():
        lines.append(f"| {result.name} | {result.value:.0f} | {result.explanation[:60]} |")

    lines.extend(["", "## Steps", ""])
    for step in trace.steps:
        status = "OK" if step.success else "FAIL"
        lines.append(f"### Step {step.step_number} [{status}]")
        lines.append(f"- **Thought:** {step.thought_summary}")
        lines.append(f"- **Action:** {step.action_type}: {step.action}")
        if step.result:
            lines.append(f"- **Result:** {step.result[:100]}")
        if step.extracted_facts:
            lines.append(f"- **Facts:** {', '.join(step.extracted_facts[:3])}")
        if step.errors:
            lines.append(f"- **Errors:** {', '.join(step.errors[:2])}")
        lines.append("")

    if trace.affordances:
        lines.extend(["## Affordances", ""])
        lines.append("| Name | Kind | Status | Relevant |")
        lines.append("|------|------|--------|----------|")
        for aff in trace.affordances[:20]:
            lines.append(f"| {aff.name[:30]} | {aff.kind} | {aff.status.value} | {'Yes' if aff.relevant else 'No'} |")

    if analysis and analysis.get("all_insights"):
        lines.extend(["", "## Insights", ""])
        for insight in analysis["all_insights"]:
            lines.append(f"- {insight}")

    lines.extend(["", "---", f"*Generated by AgentUX v0.1.0*"])
    return "\n".join(lines)
